# Generated by Django 5.1.4 on 2024-12-16 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='system.workerprofile')),
            ],
        ),
    ]
